/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Mon Apr 04 2016 12:18:55 GMT-0700 (PDT).
 */

define([
    'plugin/PluginConfig',
    'plugin/PluginBase',
    'common/util/ejs', // for ejs templates
    'common/util/xmljsonconverter', // used to save model as json
    'gridlabd/meta',
    'gridlabd/modelLoader',
    'q'
], function (
    PluginConfig,
    PluginBase,
    ejs,
    Converter,
    MetaTypes,
    loader,
    Q) {
    'use strict';

    /**
     * Initializes a new instance of SimulateWithGridlabD.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin SimulateWithGridlabD.
     * @constructor
     */
    var SimulateWithGridlabD = function () {
        // Call base class' constructor.
        PluginBase.call(this);

        this.metaTypes = MetaTypes;
    };

    // Prototypal inheritance from PluginBase.
    SimulateWithGridlabD.prototype = Object.create(PluginBase.prototype);
    SimulateWithGridlabD.prototype.constructor = SimulateWithGridlabD;

    /**
     * Gets the name of the SimulateWithGridlabD.
     * @returns {string} The name of the plugin.
     * @public
     */
    SimulateWithGridlabD.prototype.getName = function () {
        return 'SimulateWithGridlabD';
    };

    /**
     * Gets the semantic version (semver.org) of the SimulateWithGridlabD.
     * @returns {string} The version of the plugin.
     * @public
     */
    SimulateWithGridlabD.prototype.getVersion = function () {
        return '0.1.0';
    };

    /**
     * The ConfigurationStructure defines the configuration for the plugin
     * and will be used to populate the GUI when invoking the plugin from webGME.
     * @returns {object} The version of the plugin.
     * @public
     */
    SimulateWithGridlabD.prototype.getConfigStructure = function() {
        return [
	    {
		'name': 'returnZip',
		'displayName': 'Zip and return generated GLD output.',
		'description': 'If true, it enables the client to download a zip of the simulation output.',
		'value': false,
		'valueType': 'boolean',
		'readOnly': false
	    }
        ];
    };

    SimulateWithGridlabD.prototype.notify = function(level, msg) {
	var self = this;
	var prefix = self.projectId + '::' + self.projectName + '::' + level + '::';
	if (level=='error')
	    self.logger.error(msg);
	else if (level=='debug')
	    self.logger.debug(msg);
	else if (level=='info')
	    self.logger.info(msg);
	else if (level=='warning')
	    self.logger.warn(msg);
	self.createMessage(self.activeNode, msg, level);
	self.sendNotification(prefix+msg);
    };

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    SimulateWithGridlabD.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
        modelNode;

	self.result.success = false;

        if (typeof WebGMEGlobal !== 'undefined') {
	    var msg = 'You must run this plugin on the server!';
	    self.notify('error', msg);
	    callback(new Error(msg), self.result);
        }

	self.updateMETA(self.metaTypes);

	// What did the user select for our configuration?
	var currentConfig = self.getCurrentConfig();
	self.returnZip = currentConfig.returnZip;

        modelNode = self.activeNode;
	self.modelName = self.core.getAttribute(modelNode, 'name');
	self.fileName = self.modelName + '.glm';

	var path = require('path');
	var filendir = require('filendir');
	self.root_dir = path.join(process.cwd(), 
				  'generated', 
				  self.project.projectId, 
				  self.branchName,
				  'models');

	return self.checkModelFileExists()
	    .then(function() {
		return self.runSimulation();
	    })
	    .then(function() {
		return self.generateBlobArtifacts();
	    })
	    .then(function() {
		self.result.success = true;
		self.createMessage(self.activeNode, 'Simulation Complete.');
		callback(null, self.result);
	    })
	    .catch(function(err) {
		self.result.success = false;
		self.createMessage(self.activeNode, err, 'error');
		callback(err, self.result);
	    });

    };

    SimulateWithGridlabD.prototype.checkModelFileExists = function() {
	var self = this;
	var path = require('path');
	var fs = require('fs');

	self.notify('info', 'Checking existence of model file.');

	var deferred = Q.defer();

	fs.access(path.join(self.root_dir, self.fileName), (err) => {
	    if (err) {
		deferred.reject('Model file has not been generated on the server! Make sure to run GenerateGLM on the server!');
	    }
	    else {
		deferred.resolve();
	    }
	});

	return deferred.promise;
    };

    SimulateWithGridlabD.prototype.runSimulation = function() {
	var self = this;
	var path = require('path');
	var cp = require('child_process');

	self.notify('info', 'Starting Simulation');

	var deferred = Q.defer();

	var fname = path.join(self.root_dir, self.fileName);

	self.sim_stdout = '';
	self.sim_stderr = '';
	self.simProcess = cp.spawn('gridlabd', [fname], {
	    cwd: self.root_dir
	});

	self.simProcess.stdout.on('data', (data) => {
	    self.sim_stdout += data;
	});
	self.simProcess.stderr.on('data', (data) => {
	    self.sim_stderr += data;
	});
	self.simProcess.on('close', (code) => {
	    self.notify('info', 'Simulation exited with code: ' + code);
	    deferred.resolve();
	});
	
	return deferred.promise;
    };

    SimulateWithGridlabD.prototype.generateBlobArtifacts = function() {
	var self = this;
	if (!self.returnZip) {
	    self.notify('info', 'User did not request the output to be returned.');
	    return;
	}

	var path = require('path');
	var stdoutFile = self.modelName + '.stdout';
	var stderrFile = self.modelName + '.stderr';
	
	self.notify('info', 'Returning output to user.');

	return self.blobClient.putFile(stdoutFile, self.sim_stdout)
	    .then(function (hash) {
		self.result.addArtifact(hash);
	    })
	    .then(function() {
		return self.blobClient.putFile(stderrFile, self.sim_stderr);
	    })
	    .then(function (hash) {
		self.result.addArtifact(hash);
	    });
    };

    return SimulateWithGridlabD;
});
