/**
 * Generated by PluginGenerator 0.14.0 from webgme on Mon Apr 04 2016 17:15:09 GMT-0700 (PDT).
 */

define([], function () {
    'use strict';
    return {
        'auction': '/z/P',
        'capacitor': '/z/1',
        'climate': '/z/B',
        'clock': '/z/F',
        'conductor': '/z/L',
        'controller': '/z/c',
        'FCO': '/1',
        'GLD_META': '/z',
        'house': '/z/b',
        'line': '/z/f',
        'line_configuration': '/z/h',
        'line_object': '/z/x',
        'line_spacing': '/z/H',
        'load': '/z/O',
        'Model': '/z/R',
        'multi_recorder': '/z/M',
        'node': '/z/N',
        'object': '/z/A',
        'overhead_line': '/z/8',
        'overhead_line_conductor': '/z/6',
        'powerflow': '/z/o',
        'regulator': '/z/5',
        'regulator_configuration': '/z/X',
        'residential': '/z/m',
        'schedule': '/z/u',
        'schedule_entry': '/z/d',
        'switch': '/z/oT',
        'transformer': '/z/z',
        'transformer_configuration': '/z/S',
        'triplex_line': '/z/s',
        'triplex_line_conductor': '/z/k',
        'triplex_line_configuration': '/z/C',
        'triplex_meter': '/z/q',
        'triplex_node': '/z/D',
        'underground_line': '/z/T',
        'underground_line_conductor': '/z/p',
        'waterheater': '/z/0',
    };
});