/**
 * Generated by PluginGenerator 1.7.0 from webgme on Fri May 06 2016 13:33:41 GMT-0500 (Central Daylight Time).
 */

define([], function () {
    'use strict';
    return {
        'Class': '/z/7',
        'FCO': '/1',
        'Language': '/z',
        'Model': '/z/R',
        'Module': '/z/E',
        'Object': '/z/A',
        'Parent': '/z/X1',
    };
});