/**
 * Generated by PluginGenerator 1.7.0 from webgme on Fri May 06 2016 13:33:41 GMT-0500 (Central Daylight Time).
 */

define([], function () {
    'use strict';
    return {
        'Class': '/0/J',
        'FCO': '/1',
        'Language': '/0',
        'Model': '/0/b',
        'Module': '/0/l',
        'Object': '/0/2',
        'Parent': '/0/4',
    };
});
